title: "Davis Haupt"
baseurl: /
languageCode: en-us
theme: custom

permalinks:
  blog: /blog/:year/:month/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango

params:
  sitename: "Davis Haupt"
  author: "Davis Haupt"
