title: "Davis Haupt's Website"
baseurl: https://davi.sh/
languageCode: en-us
theme: custom
enableRobotsTXT: true

permalinks:
  blog: /blog/:year/:month/:filename/

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    style: tango

params:
  sitename: "Davis Haupt"
  author: "Davis Haupt"
